### ISSUE TITLE
Sample App not working

### ISSUE THREAD

**Issue by ISSPRO-Eng** [Laerdal/Laerdal.Dfu#16]
**Describe the bug**
Running Sample Project crashes when searching for devices in iOS sample.

**To Reproduce**
Download and run sample to iOS divide with iOS 16. Search fro devices

**Expected behavior**
A list of BT devices to appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 13
 - Browser Safari
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16
 - Browser Safari

**Additional context**
Crashes in Main.cs

**Comment by nissaba** [comment]
Where can we get this sample app?

**Comment by ISSPRO-Eng** [comment]
Added you to the repo @nissaba

**Comment by ISSPRO-Eng** [comment]
@nissaba any luck?
