### ISSUE TITLE
Add timeout support

### ISSUE THREAD

**Issue by haoyuant** [Laerdal/Laerdal.Dfu#4]
Hello, thanks for creating this awesome library, it really saves my life : )
Just want to know would it provide connection timeout option in the future versions? Looks like the current version will wait for the device to enter bootloader mode without timeout, it would be good to trigger a timeout error so that the app can show a warning dialog to the user.

**Comment by framinosona** [comment]
Hi, thanks! I completely agree that it would be nice, though I merely wrap the native libraries here (apart from interpreting the feedback I receive from it). 
One thing that will come soon is that I will expose all the DfuServiceInitiator configuration more easily in the DfuInstallation ... Idk if it helps.

**Comment by framinosona** [comment]
Thing is if the update times out it's not certain that a retry would fix it. You might want to ask your user if they want to retry or not.

**Comment by haoyuant** [comment]
Thanks for your replies! Exposing more configuration sounds good : ) Yea, retry might not fix the problem, but at least can let the user know the DFU target is not reachable for some reasons. Actually this situation is not very rare in my case, the client has a big factory to produce boards that heavily use BLE which may cause unstable advertising and connection happen occasionally.

**Comment by framinosona** [comment]
Here is what has been pushed, let me know if you see something that needs to be changed or added. 

``csharp

        #region DfuInitiator Shared Configuration

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetDeviceName(string name)
        /// iOS :
        ///     public string? AlternativeAdvertisingName {get; set;}
        ///     public bool AlternativeAdvertisingNameEnabled {get; set;}
        /// </summary>
        public string AlternativeAdvertisingName
        {
            get => GetValue<string>();
            set => SetValue(value);
        }

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetPrepareDataObjectDelay(long delay)
        /// iOS :
        ///     public double DataObjectPreparationDelay {get; set;}
        /// </summary>
        public double? DataObjectPreparationDelay
        {
            get => GetValue<double?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator DisableResume()
        /// iOS :
        ///     public bool DisableResume {get; set;}
        /// </summary>
        public bool? DisableResume
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetUnsafeExperimentalButtonlessServiceInSecureDfuEnabled(bool enable)
        /// iOS :
        ///     public bool EnableUnsafeExperimentalButtonlessServiceInSecureDfu {get; set;}
        /// </summary>
        public bool? EnableUnsafeExperimentalButtonlessServiceInSecureDfu
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetForceDfu(bool force)
        /// iOS :
        ///     public bool ForceDfu {get; set;}
        /// </summary>
        public bool? ForceDfu
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetForceScanningForNewAddressInLegacyDfu(bool force)
        /// iOS :
        ///     public bool ForceScanningForNewAddressInLegacyDfu {get; set;}
        /// </summary>
        public bool? ForceScanningForNewAddressInLegacyDfu
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }

        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetPacketsReceiptNotificationsEnabled(bool enabled)
        ///     public DfuServiceInitiator SetPacketsReceiptNotificationsValue(int number)
        /// iOS :
        ///     public ushort PacketReceiptNotificationParameter {get; set;}
        /// </summary>
        public ushort? PacketReceiptNotificationParameter
        {
            get => GetValue<ushort?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator DisableMtuRequest()
        /// </summary>
        public bool? DisableMtuRequest
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetDisableNotification(bool disableNotification)
        /// </summary>
        public bool? DisableNotification
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public const int DefaultMbrSize = 4096;
        ///     public DfuServiceInitiator SetMbrSize(int mbrSize)
        /// </summary>
        public int? MbrSize
        {
            get => GetValue<int?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetScope(int scope)
        ///     public const int ScopeApplication = 2;
        ///     public const int ScopeSystemComponents = 1;
        /// </summary>
        public DfuServiceScope? Scope
        {
            get => GetValue<DfuServiceScope?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetForeground(bool foreground)
        /// </summary>
        public bool? Foreground
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetKeepBond(bool keepBond)
        /// </summary>
        public bool? KeepBond
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetRestoreBond(bool keepBond)
        /// </summary>
        public bool? RestoreBond
        {
            get => GetValue<bool?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetMtu(int mtu)
        /// </summary>
        public int? Mtu
        {
            get => GetValue<int?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// Android :
        ///     public DfuServiceInitiator SetNumberOfRetries(int max)
        /// </summary>
        public int? NumberOfRetries
        {
            get => GetValue<int?>();
            set => SetValue(value);
        }
        
        /// <summary>
        /// iOS :
        ///     public double ConnectionTimeout {get; set;}
        /// </summary>
        public long? ConnectionTimeout
        {
            get => GetValue<long?>();
            set => SetValue(value);
        }
        
        // TODO : CustomUuids
        
        #endregion
```

**Comment by framinosona** [comment]
Be careful, the default configuration was before: 
EnableUnsafeExperimentalButtonlessServiceInSecureDfu = true
DisableNotification = true

But now you need to set it yourself: 
DfuInstallation.EnableUnsafeExperimentalButtonlessServiceInSecureDfu = true;
DfuInstallation.DisableNotification = true;

**Comment by haoyuant** [comment]
That commit looks good, it makes the configuration easier😀
