### ISSUE TITLE
.Net 8 Support

### ISSUE THREAD

**Issue by Justles** [Laerdal/Laerdal.Dfu#45]
With .Net 7 end of life ending on May 14th 2024, is there a timeline to support .Net 8? I noticed some beta versions but unsure if those were related.

Thanks.

**Comment by ISSPRO-Eng** [comment]
@Justles The current nuget supports .NET 8. It works on Android, but it looks like they are working on fixing the iOS issues

**Comment by Justles** [comment]
I can verify the initial question is answered and does work on .Net 8 but getting mixed results due to Android 34 so will close this.

**Comment by ISSPRO-Eng** [comment]
@Justles Upgraded to the latest nuget and now Android does not work with Android 34 as the target
