### ISSUE TITLE
Android 14 Error when Starting DFU Process

### ISSUE THREAD

**Issue by ISSPRO-Eng** [Laerdal/Laerdal.Dfu#49]
I have added the newly released Laerdal.Dfu Nuget V1.27.76. I am able to perform DFU updates on my iOS application in .NET Maui, but I am running into an error when performing the update on an Android phone running Version 14 (API 34). 

Unable to create service crc64f81dc64610be9973.DfuService: java.lang.SecurityException: com.isspro.ev3_attribute_programmer: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

Here is the stack trace 

[DfuBaseService] DFU service created. Version: 2.3.0
[BluetoothAdapter] BluetoothAdapter() : com.isspro.ev3_attribute_programmer
[AndroidRuntime] Shutting down VM
[gralloc4] @set_metadata: update dataspace from GM (0x00000000 -> 0x08010000)
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.isspro.ev3_attribute_programmer, PID: 16189
[AndroidRuntime] java.lang.RuntimeException: Unable to create service crc64f81dc64610be9973.DfuService: java.lang.SecurityException: com.isspro.ev3_attribute_programmer: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
[AndroidRuntime] 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:230)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:319)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8893)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
[AndroidRuntime] Caused by: java.lang.SecurityException: com.isspro.ev3_attribute_programmer: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[AndroidRuntime] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
[AndroidRuntime] 	at android.os.Parcel.createException(Parcel.java:3053)
[AndroidRuntime] 	at android.os.Parcel.readException(Parcel.java:3036)
[AndroidRuntime] 	at android.os.Parcel.readException(Parcel.java:2978)
[AndroidRuntime] 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
[AndroidRuntime] 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
[AndroidRuntime] 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
[AndroidRuntime] 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
[AndroidRuntime] 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
[AndroidRuntime] 	at no.nordicsemi.android.dfu.DfuBaseService.onCreate(DfuBaseService.java:1038)
[AndroidRuntime] 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
[AndroidRuntime] 	... 9 more
[AndroidRuntime] Caused by: android.os.RemoteException: Remote stack trace:
[AndroidRuntime] 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16585)
[AndroidRuntime] 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
[AndroidRuntime] 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
[AndroidRuntime] 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
[AndroidRuntime] 	at android.os.Binder.execTransactInternal(Binder.java:1375)
[AndroidRuntime]

**Comment by Justles** [comment]
Also tested and have the same issue.

After looking alittle, I think the current Nordic SDK for Android is still pointing to 2.3.1 in the [Laerdal.Dfu.Bindings.Android nuget](https://github.com/Laerdal/Laerdal.Dfu.Bindings.Android), as it based on https://github.com/NordicSemiconductor/Android-DFU-Library/issues/412 it was pushed as an update in 2.4.0 which may resolve this but I'm not familiar enough to make this correction or to verify more..

**Comment by ISSPRO-Eng** [comment]
@framinosana and @ksidirop-laerdal are the maintainers. They should know more information, but I would agree that pointing at the update library would probably fix it.
