### ISSUE TITLE
Failed to submit to App Store Connect & large app size

### ISSUE THREAD

**Issue by haoyuant** [Laerdal/Laerdal.Dfu#5]
Hi, when I tried submitting the app to App Store Connect, I got this error:
```
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Fliteboard.iOS.app/Frameworks/ZIPFoundation.framework' contains disallowed file 'Frameworks'."

ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Fliteboard.iOS.app/Frameworks/iOSDFULibrary.framework' contains disallowed file 'Frameworks'."
```

I tried that known issue's solution https://github.com/xamarin/XamarinComponents/issues/993, but unfortunately it didn't fix the problem.

Also, I notice that the app size is way bigger than the previous builds after I added this library. It grows from 32MB to 220MB, is there a way to trim the build?

**Comment by SuperCorks** [comment]
@haoyuant Still experiencing the issue?

**Comment by haoyuant** [comment]
@SuperCorks I've tested the latest version(beta 12) and the app bundle size is much smaller now, without using this library my app size was ~32MB, now is ~46MB, which is good. And it can be uploaded to App Store Connect without problems. Although I didn't test it throughly like regression testing or submit for App Store Review, I think it does fix the problems I previously have.
