### ISSUE TITLE
(iOS) SwiftSupport error when Archiving an app that references the Dfu package via an iOS library project

### ISSUE THREAD

**Issue by SuperCorks** [Laerdal/Laerdal.Dfu#6]
We've been having issues archiving iOS apps that reference an iOS library that imports the `Laerdal.Dfu` package. Although when the code from the library project is copied into the app, the archiving issues are resolved.

[iOS App] -> [Laerdal.Dfu] = **(OK)**
[iOS App] -> [iOS Library] -> [Laerdal.Dfu] = **(Archiving issues)**

**To Reproduce**
1. Open the following solution [sample-dfu-app.zip](https://github.com/Laerdal/Laerdal.Dfu/files/6577230/sample-dfu-app.zip)
1. Set the build configuration to Release
2. Archive the `sample-dfu-app-import.iOS` project which refers to the `Laerdal.Dfu` package via the `dfu-iOS` library.
3. You should get the following error:
```
Target "_SRSCopySwiftSupport" in file "/Users/carl/.nuget/packages/xamarin.ios.swiftruntimesupport/0.2.0/buildTransitive/Xamarin.iOS.SwiftRuntimeSupport.targets":
  Task "Message"
    Copying SwiftSupport folder from obj/Release/SwiftSupport to /SwiftSupport folder.
  Done executing task "Message".
  Using "Ditto" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll".
  Task "Ditto"
    /usr/bin/ditto -rsrc obj/Release/SwiftSupport /SwiftSupport 
    ditto: Cannot get the real path for source 'obj/Release/SwiftSupport'
    /Users/carl/.nuget/packages/xamarin.ios.swiftruntimesupport/0.2.0/buildTransitive/Xamarin.iOS.SwiftRuntimeSupport.targets(25,9): error MSB6006: "ditto" exited with code 1.
  Done executing task "Ditto" -- FAILED.
Done building target "_SRSCopySwiftSupport" in project "dfu-iOS.csproj" -- FAILED.
Done building project "dfu-iOS.csproj" -- FAILED.
```
5. Archive the "sample-dfu-app.iOS" project which refers to the `Laerdal.Dfu` package directly.
6. You should get an error related to the provisioning profile, which means `ditto` process ran successfully during the build.

**Expected behavior**
The ditto process should run successfully when building the iOS library for an archive.

**Additional Context**
Note that it's only when building for an archive that this happens. Building for a debug run works without any issue.

I'm not sure whether this is something that can be fixed by this you guys, but if you have any idea on how I can fix this, it'd be appreciated.

**Work Around**
Reference to the code directly in the iOS app project. Don't use a library project.

**Comment by SuperCorks** [comment]
Hey guys is this the right place for this issue or should I have posted it in https://github.com/Laerdal/Laerdal.Dfu.iOS? There's no hurry as there is a workaround, but I just want to be sure this has been seen.

**Comment by framinosona** [comment]
Hey @SuperCorks , sorry I missed this issue. 
It's the perfect place to post it :) 

Okay so actually you're not the first to report that behavior, but you're the first to provide a sample that will make it easy to reproduce and try to fix! 
I'll try to have a look into it this weekend, a colleague of mine suggested me some linking tweaks that would prevent that kind of issues.

**Comment by raindeer** [comment]
Any updates on this?

**Comment by raindeer** [comment]
including https://www.nuget.org/packages/Xamarin.Swift/ fixes the issue

**Comment by SuperCorks** [comment]
@raindeer you include in where?
- the iOS app project
- the iOS library project that references Laerdal.Dfu
- in the source code of this Github repo?

**Comment by AntAttakk** [comment]
Hi @SuperCorks. I work with @raindeer. We have a Xamarin.Forms project that imports the `Laerdal.Dfu` package, and we import `Xamarin.Swift` in the corresponding iOS app project.

**Comment by SuperCorks** [comment]
Epic thanks guys!

@framinosona I'll let you decide whether you want to close this issue as-is (maybe add a quick requirement to the readme) or if you want to change the code of the project in order to avoid requiring that additional import.

**Comment by framinosona** [comment]
Hey guys, sorry I had some issues in my private life I couldn't come back to it before now. 
Awesome news you found a workaround, do you think adding it as PackageReference would work ?
There is already: https://github.com/Laerdal/Laerdal.Dfu/blob/8b5a2fc23c48e8cd7ade4a4eefffca1d76395cc2/Laerdal.Dfu/Laerdal.Dfu.csproj#L117
Otherwise yeah @SuperCorks we can add it in the Readme

**Comment by framinosona** [comment]
Version 0.2.17 has this added PackageReference. Also updated the iOS side to the latest of Nordic's releases

https://www.nuget.org/packages/Laerdal.Dfu/0.2.17
