### ISSUE TITLE
Could not obtain peripheral instance

### ISSUE THREAD

**Issue by jkandiko** [Laerdal/Laerdal.Dfu#7]
**Describe the bug**
When I try to do a DFU update in iOS, I get a Could not obtain peripheral instance BluetoothDisabled error.  The dfu installation goes through the connecting state but immediately errors out.  Bluetooth is enabled, the address is valid, and so is the file path.  There appears to be something similar to [https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/256](here) but they are developing directly in swift / objective-c.  

**To Reproduce**
dfuInstallation = new Laerdal.Dfu.DfuInstallation("00000000-0000-0000-0000-ccdc94eb087e", "var/mobile/Containers/Data/Application/17764959-22A4-4C19-A02B-62C1EF23E20B/Documents/.config/Sdk14_nRF52_v37p14_APP_pkg.zip");
dfuInstallation.PropertyChanged += Dfu_PropertyChanged;
dfuInstallation.ErrorOccured += DfuInstallation_ErrorOccured;
dfuInstallation.ProgressChanged += DfuInstallation_ProgressChanged;
 dfuInstallation.StateChanged += DfuInstallation_StateChanged;
dfuInstallation.Start();

**Expected behavior**
I would have expected the app to work the same as the android version (which updates fine);

**Desktop (please complete the following information):**
-Visual Studio Community 2019 - 16.10.2
- Xamarin.iOS and Xamarin.Mac SDK - 14.20.0.10

**Smartphone (please complete the following information):**
-iPhone 11 14.6

**Comment by framinosona** [comment]
Hi, are you connected to the device? Like, on your own CBCentralManager. The call to Start() will internally create it's own CBCentralManager and try to find the provided device, connect to it etc. If your CBCentralManager on your end is connected to it, Nordic's CBCentralManager won't see it.
Same as if you were connected to a bluetooth device with an Android phone, your iOS phone would not see it anymore/not receive advertisment.
